### ISSUE TITLE
File Missing Error

### ISSUE THREAD

**Issue by m-maaz-azhar** [Muhammad-Hasham-Khalid/PDF_viewer_pdfjs#1]
The file is available on the exact location but it is showing this error.
**Error:**  _Missing PDF "file:///D:/PDF_viewer_pdfjs-master/docs/pdf.pdf"_

**Comment by Muhammad-Hasham-Khalid** [comment]
Actually there are 2 things,
1) I had misspelled the filename in js/main.js, line-1 which i have corrected now, thanks.
2) Secondly, the library PDF.js needs a server to run so may be you can use the live server extension in VS Code https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer to run the project.
